/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AttachmentResponseDto } from '../models';
/**
 * AttachmentsApi - axios parameter creator
 * @export
 */
export const AttachmentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete an attachment
         * @param {string} id Attachment ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attachmentControllerDeleteAttachment: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('attachmentControllerDeleteAttachment', 'id', id)
            const localVarPath = `/attachments/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Download attachment file
         * @param {string} id Attachment ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attachmentControllerDownloadFile: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('attachmentControllerDownloadFile', 'id', id)
            const localVarPath = `/attachments/{id}/download`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get attachment details by ID
         * @param {string} id Attachment ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attachmentControllerFindById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('attachmentControllerFindById', 'id', id)
            const localVarPath = `/attachments/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get attachments for a message
         * @param {string} messageId Message ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attachmentControllerFindByMessage: async (messageId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'messageId' is not null or undefined
            assertParamExists('attachmentControllerFindByMessage', 'messageId', messageId)
            const localVarPath = `/attachments/message/{messageId}`
                .replace(`{${"messageId"}}`, encodeURIComponent(String(messageId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get attachments for a project
         * @param {string} projectId Project ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attachmentControllerFindByProject: async (projectId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('attachmentControllerFindByProject', 'projectId', projectId)
            const localVarPath = `/attachments/project/{projectId}`
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get attachments for a task
         * @param {string} taskId Task ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attachmentControllerFindByTask: async (taskId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('attachmentControllerFindByTask', 'taskId', taskId)
            const localVarPath = `/attachments/task/{taskId}`
                .replace(`{${"taskId"}}`, encodeURIComponent(String(taskId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload an attachment
         * @param {File} file File to upload
         * @param {string} [taskId] ID of the task this attachment belongs to
         * @param {string} [projectId] ID of the project this attachment belongs to
         * @param {string} [messageId] ID of the message this attachment belongs to
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attachmentControllerUploadFile: async (file: File, taskId?: string, projectId?: string, messageId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'file' is not null or undefined
            assertParamExists('attachmentControllerUploadFile', 'file', file)
            const localVarPath = `/attachments/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (file !== undefined) {
                localVarQueryParameter['file'] = file;
            }

            if (taskId !== undefined) {
                localVarQueryParameter['taskId'] = taskId;
            }

            if (projectId !== undefined) {
                localVarQueryParameter['projectId'] = projectId;
            }

            if (messageId !== undefined) {
                localVarQueryParameter['messageId'] = messageId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AttachmentsApi - functional programming interface
 * @export
 */
export const AttachmentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AttachmentsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Delete an attachment
         * @param {string} id Attachment ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async attachmentControllerDeleteAttachment(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.attachmentControllerDeleteAttachment(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttachmentsApi.attachmentControllerDeleteAttachment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Download attachment file
         * @param {string} id Attachment ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async attachmentControllerDownloadFile(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.attachmentControllerDownloadFile(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttachmentsApi.attachmentControllerDownloadFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get attachment details by ID
         * @param {string} id Attachment ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async attachmentControllerFindById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AttachmentResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.attachmentControllerFindById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttachmentsApi.attachmentControllerFindById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get attachments for a message
         * @param {string} messageId Message ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async attachmentControllerFindByMessage(messageId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AttachmentResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.attachmentControllerFindByMessage(messageId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttachmentsApi.attachmentControllerFindByMessage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get attachments for a project
         * @param {string} projectId Project ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async attachmentControllerFindByProject(projectId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AttachmentResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.attachmentControllerFindByProject(projectId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttachmentsApi.attachmentControllerFindByProject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get attachments for a task
         * @param {string} taskId Task ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async attachmentControllerFindByTask(taskId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AttachmentResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.attachmentControllerFindByTask(taskId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttachmentsApi.attachmentControllerFindByTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Upload an attachment
         * @param {File} file File to upload
         * @param {string} [taskId] ID of the task this attachment belongs to
         * @param {string} [projectId] ID of the project this attachment belongs to
         * @param {string} [messageId] ID of the message this attachment belongs to
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async attachmentControllerUploadFile(file: File, taskId?: string, projectId?: string, messageId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AttachmentResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.attachmentControllerUploadFile(file, taskId, projectId, messageId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttachmentsApi.attachmentControllerUploadFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AttachmentsApi - factory interface
 * @export
 */
export const AttachmentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AttachmentsApiFp(configuration)
    return {
        /**
         * 
         * @summary Delete an attachment
         * @param {string} id Attachment ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attachmentControllerDeleteAttachment(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.attachmentControllerDeleteAttachment(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Download attachment file
         * @param {string} id Attachment ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attachmentControllerDownloadFile(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.attachmentControllerDownloadFile(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get attachment details by ID
         * @param {string} id Attachment ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attachmentControllerFindById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<AttachmentResponseDto> {
            return localVarFp.attachmentControllerFindById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get attachments for a message
         * @param {string} messageId Message ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attachmentControllerFindByMessage(messageId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<AttachmentResponseDto>> {
            return localVarFp.attachmentControllerFindByMessage(messageId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get attachments for a project
         * @param {string} projectId Project ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attachmentControllerFindByProject(projectId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<AttachmentResponseDto>> {
            return localVarFp.attachmentControllerFindByProject(projectId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get attachments for a task
         * @param {string} taskId Task ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attachmentControllerFindByTask(taskId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<AttachmentResponseDto>> {
            return localVarFp.attachmentControllerFindByTask(taskId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload an attachment
         * @param {File} file File to upload
         * @param {string} [taskId] ID of the task this attachment belongs to
         * @param {string} [projectId] ID of the project this attachment belongs to
         * @param {string} [messageId] ID of the message this attachment belongs to
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attachmentControllerUploadFile(file: File, taskId?: string, projectId?: string, messageId?: string, options?: RawAxiosRequestConfig): AxiosPromise<AttachmentResponseDto> {
            return localVarFp.attachmentControllerUploadFile(file, taskId, projectId, messageId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AttachmentsApi - object-oriented interface
 * @export
 * @class AttachmentsApi
 * @extends {BaseAPI}
 */
export class AttachmentsApi extends BaseAPI {
    /**
     * 
     * @summary Delete an attachment
     * @param {string} id Attachment ID (UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentsApi
     */
    public attachmentControllerDeleteAttachment(id: string, options?: RawAxiosRequestConfig) {
        return AttachmentsApiFp(this.configuration).attachmentControllerDeleteAttachment(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Download attachment file
     * @param {string} id Attachment ID (UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentsApi
     */
    public attachmentControllerDownloadFile(id: string, options?: RawAxiosRequestConfig) {
        return AttachmentsApiFp(this.configuration).attachmentControllerDownloadFile(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get attachment details by ID
     * @param {string} id Attachment ID (UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentsApi
     */
    public attachmentControllerFindById(id: string, options?: RawAxiosRequestConfig) {
        return AttachmentsApiFp(this.configuration).attachmentControllerFindById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get attachments for a message
     * @param {string} messageId Message ID (UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentsApi
     */
    public attachmentControllerFindByMessage(messageId: string, options?: RawAxiosRequestConfig) {
        return AttachmentsApiFp(this.configuration).attachmentControllerFindByMessage(messageId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get attachments for a project
     * @param {string} projectId Project ID (UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentsApi
     */
    public attachmentControllerFindByProject(projectId: string, options?: RawAxiosRequestConfig) {
        return AttachmentsApiFp(this.configuration).attachmentControllerFindByProject(projectId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get attachments for a task
     * @param {string} taskId Task ID (UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentsApi
     */
    public attachmentControllerFindByTask(taskId: string, options?: RawAxiosRequestConfig) {
        return AttachmentsApiFp(this.configuration).attachmentControllerFindByTask(taskId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload an attachment
     * @param {File} file File to upload
     * @param {string} [taskId] ID of the task this attachment belongs to
     * @param {string} [projectId] ID of the project this attachment belongs to
     * @param {string} [messageId] ID of the message this attachment belongs to
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentsApi
     */
    public attachmentControllerUploadFile(file: File, taskId?: string, projectId?: string, messageId?: string, options?: RawAxiosRequestConfig) {
        return AttachmentsApiFp(this.configuration).attachmentControllerUploadFile(file, taskId, projectId, messageId, options).then((request) => request(this.axios, this.basePath));
    }
}

