/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
    DUMMY_BASE_URL,
    assertParamExists,
    setApiKeyToObject,
    setBasicAuthToObject,
    setBearerAuthToObject,
    setOAuthToObject,
    setSearchParams,
    serializeDataIfNeeded,
    toPathString,
    createRequestFunction
} from '../common';
// @ts-ignore
import {
    BASE_PATH,
    COLLECTION_FORMATS,
    type RequestArgs,
    BaseAPI,
    RequiredError,
    operationServerMap
} from '../base';
// @ts-ignore
import type { CreateNotificationDto } from '../models';
// @ts-ignore
import type { NotificationResponseDto } from '../models';
// @ts-ignore
import type { UpdateNotificationDto } from '../models';
/**
 * NotificationsApi - axios parameter creator
 * @export
 */
export const NotificationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @summary Create a new notification
         * @param {CreateNotificationDto} createNotificationDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerCreate: async (
            createNotificationDto: CreateNotificationDto,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'createNotificationDto' is not null or undefined
            assertParamExists(
                'notificationControllerCreate',
                'createNotificationDto',
                createNotificationDto
            );
            const localVarPath = `/notifications`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };
            localVarRequestOptions.data = serializeDataIfNeeded(
                createNotificationDto,
                localVarRequestOptions,
                configuration
            );

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         *
         * @summary Delete a notification
         * @param {string} id Notification ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerDeleteNotification: async (
            id: string,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('notificationControllerDeleteNotification', 'id', id);
            const localVarPath = `/notifications/{id}`.replace(
                `{${'id'}}`,
                encodeURIComponent(String(id))
            );
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         *
         * @summary Get notification by ID
         * @param {string} id Notification ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerFindById: async (
            id: string,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('notificationControllerFindById', 'id', id);
            const localVarPath = `/notifications/{id}`.replace(
                `{${'id'}}`,
                encodeURIComponent(String(id))
            );
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         *
         * @summary Get notifications for a user (own notifications or admin access)
         * @param {string} userId User ID (UUID)
         * @param {NotificationControllerFindByUserTypeEnum} [type] Filter by notification type
         * @param {boolean} [isRead] Filter by read status
         * @param {number} [limit] Limit results
         * @param {number} [offset] Offset results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerFindByUser: async (
            userId: string,
            type?: NotificationControllerFindByUserTypeEnum,
            isRead?: boolean,
            limit?: number,
            offset?: number,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('notificationControllerFindByUser', 'userId', userId);
            const localVarPath = `/notifications/user/{userId}`.replace(
                `{${'userId'}}`,
                encodeURIComponent(String(userId))
            );
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            if (isRead !== undefined) {
                localVarQueryParameter['isRead'] = isRead;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         *
         * @summary Get notifications for the current user
         * @param {NotificationControllerGetMyNotificationsTypeEnum} [type] Filter by notification type
         * @param {boolean} [isRead] Filter by read status
         * @param {number} [limit] Limit results
         * @param {number} [offset] Offset results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerGetMyNotifications: async (
            type?: NotificationControllerGetMyNotificationsTypeEnum,
            isRead?: boolean,
            limit?: number,
            offset?: number,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            const localVarPath = `/notifications/my-notifications`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            if (isRead !== undefined) {
                localVarQueryParameter['isRead'] = isRead;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         *
         * @summary Get unread notification count for current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerGetMyUnreadCount: async (
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            const localVarPath = `/notifications/my-unread-count`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         *
         * @summary Get unread notification count for a user (own count or admin access)
         * @param {string} userId User ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerGetUnreadCount: async (
            userId: string,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('notificationControllerGetUnreadCount', 'userId', userId);
            const localVarPath = `/notifications/user/{userId}/unread-count`.replace(
                `{${'userId'}}`,
                encodeURIComponent(String(userId))
            );
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         *
         * @summary Mark all notifications as read for a user (own notifications or admin access)
         * @param {string} userId User ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerMarkAllAsRead: async (
            userId: string,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('notificationControllerMarkAllAsRead', 'userId', userId);
            const localVarPath = `/notifications/user/{userId}/mark-all-read`.replace(
                `{${'userId'}}`,
                encodeURIComponent(String(userId))
            );
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         *
         * @summary Mark all notifications as read for the current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerMarkMyNotificationsAsRead: async (
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            const localVarPath = `/notifications/mark-all-read`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         *
         * @summary Update notification (mark as read/unread)
         * @param {string} id Notification ID (UUID)
         * @param {UpdateNotificationDto} updateNotificationDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerUpdate: async (
            id: string,
            updateNotificationDto: UpdateNotificationDto,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('notificationControllerUpdate', 'id', id);
            // verify required parameter 'updateNotificationDto' is not null or undefined
            assertParamExists(
                'notificationControllerUpdate',
                'updateNotificationDto',
                updateNotificationDto
            );
            const localVarPath = `/notifications/{id}`.replace(
                `{${'id'}}`,
                encodeURIComponent(String(id))
            );
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };
            localVarRequestOptions.data = serializeDataIfNeeded(
                updateNotificationDto,
                localVarRequestOptions,
                configuration
            );

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        }
    };
};

/**
 * NotificationsApi - functional programming interface
 * @export
 */
export const NotificationsApiFp = function (configuration?: Configuration) {
    const localVarAxiosParamCreator = NotificationsApiAxiosParamCreator(configuration);
    return {
        /**
         *
         * @summary Create a new notification
         * @param {CreateNotificationDto} createNotificationDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationControllerCreate(
            createNotificationDto: CreateNotificationDto,
            options?: RawAxiosRequestConfig
        ): Promise<
            (axios?: AxiosInstance, basePath?: string) => AxiosPromise<NotificationResponseDto>
        > {
            const localVarAxiosArgs = await localVarAxiosParamCreator.notificationControllerCreate(
                createNotificationDto,
                options
            );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['NotificationsApi.notificationControllerCreate']?.[
                    localVarOperationServerIndex
                ]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Delete a notification
         * @param {string} id Notification ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationControllerDeleteNotification(
            id: string,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs =
                await localVarAxiosParamCreator.notificationControllerDeleteNotification(
                    id,
                    options
                );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['NotificationsApi.notificationControllerDeleteNotification']?.[
                    localVarOperationServerIndex
                ]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get notification by ID
         * @param {string} id Notification ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationControllerFindById(
            id: string,
            options?: RawAxiosRequestConfig
        ): Promise<
            (axios?: AxiosInstance, basePath?: string) => AxiosPromise<NotificationResponseDto>
        > {
            const localVarAxiosArgs =
                await localVarAxiosParamCreator.notificationControllerFindById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['NotificationsApi.notificationControllerFindById']?.[
                    localVarOperationServerIndex
                ]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get notifications for a user (own notifications or admin access)
         * @param {string} userId User ID (UUID)
         * @param {NotificationControllerFindByUserTypeEnum} [type] Filter by notification type
         * @param {boolean} [isRead] Filter by read status
         * @param {number} [limit] Limit results
         * @param {number} [offset] Offset results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationControllerFindByUser(
            userId: string,
            type?: NotificationControllerFindByUserTypeEnum,
            isRead?: boolean,
            limit?: number,
            offset?: number,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs =
                await localVarAxiosParamCreator.notificationControllerFindByUser(
                    userId,
                    type,
                    isRead,
                    limit,
                    offset,
                    options
                );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['NotificationsApi.notificationControllerFindByUser']?.[
                    localVarOperationServerIndex
                ]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get notifications for the current user
         * @param {NotificationControllerGetMyNotificationsTypeEnum} [type] Filter by notification type
         * @param {boolean} [isRead] Filter by read status
         * @param {number} [limit] Limit results
         * @param {number} [offset] Offset results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationControllerGetMyNotifications(
            type?: NotificationControllerGetMyNotificationsTypeEnum,
            isRead?: boolean,
            limit?: number,
            offset?: number,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs =
                await localVarAxiosParamCreator.notificationControllerGetMyNotifications(
                    type,
                    isRead,
                    limit,
                    offset,
                    options
                );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['NotificationsApi.notificationControllerGetMyNotifications']?.[
                    localVarOperationServerIndex
                ]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get unread notification count for current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationControllerGetMyUnreadCount(
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs =
                await localVarAxiosParamCreator.notificationControllerGetMyUnreadCount(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['NotificationsApi.notificationControllerGetMyUnreadCount']?.[
                    localVarOperationServerIndex
                ]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get unread notification count for a user (own count or admin access)
         * @param {string} userId User ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationControllerGetUnreadCount(
            userId: string,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs =
                await localVarAxiosParamCreator.notificationControllerGetUnreadCount(
                    userId,
                    options
                );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['NotificationsApi.notificationControllerGetUnreadCount']?.[
                    localVarOperationServerIndex
                ]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Mark all notifications as read for a user (own notifications or admin access)
         * @param {string} userId User ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationControllerMarkAllAsRead(
            userId: string,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs =
                await localVarAxiosParamCreator.notificationControllerMarkAllAsRead(
                    userId,
                    options
                );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['NotificationsApi.notificationControllerMarkAllAsRead']?.[
                    localVarOperationServerIndex
                ]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Mark all notifications as read for the current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationControllerMarkMyNotificationsAsRead(
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs =
                await localVarAxiosParamCreator.notificationControllerMarkMyNotificationsAsRead(
                    options
                );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap[
                    'NotificationsApi.notificationControllerMarkMyNotificationsAsRead'
                ]?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Update notification (mark as read/unread)
         * @param {string} id Notification ID (UUID)
         * @param {UpdateNotificationDto} updateNotificationDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationControllerUpdate(
            id: string,
            updateNotificationDto: UpdateNotificationDto,
            options?: RawAxiosRequestConfig
        ): Promise<
            (axios?: AxiosInstance, basePath?: string) => AxiosPromise<NotificationResponseDto>
        > {
            const localVarAxiosArgs = await localVarAxiosParamCreator.notificationControllerUpdate(
                id,
                updateNotificationDto,
                options
            );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['NotificationsApi.notificationControllerUpdate']?.[
                    localVarOperationServerIndex
                ]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        }
    };
};

/**
 * NotificationsApi - factory interface
 * @export
 */
export const NotificationsApiFactory = function (
    configuration?: Configuration,
    basePath?: string,
    axios?: AxiosInstance
) {
    const localVarFp = NotificationsApiFp(configuration);
    return {
        /**
         *
         * @summary Create a new notification
         * @param {CreateNotificationDto} createNotificationDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerCreate(
            createNotificationDto: CreateNotificationDto,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<NotificationResponseDto> {
            return localVarFp
                .notificationControllerCreate(createNotificationDto, options)
                .then(request => request(axios, basePath));
        },
        /**
         *
         * @summary Delete a notification
         * @param {string} id Notification ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerDeleteNotification(
            id: string,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<void> {
            return localVarFp
                .notificationControllerDeleteNotification(id, options)
                .then(request => request(axios, basePath));
        },
        /**
         *
         * @summary Get notification by ID
         * @param {string} id Notification ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerFindById(
            id: string,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<NotificationResponseDto> {
            return localVarFp
                .notificationControllerFindById(id, options)
                .then(request => request(axios, basePath));
        },
        /**
         *
         * @summary Get notifications for a user (own notifications or admin access)
         * @param {string} userId User ID (UUID)
         * @param {NotificationControllerFindByUserTypeEnum} [type] Filter by notification type
         * @param {boolean} [isRead] Filter by read status
         * @param {number} [limit] Limit results
         * @param {number} [offset] Offset results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerFindByUser(
            userId: string,
            type?: NotificationControllerFindByUserTypeEnum,
            isRead?: boolean,
            limit?: number,
            offset?: number,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<void> {
            return localVarFp
                .notificationControllerFindByUser(userId, type, isRead, limit, offset, options)
                .then(request => request(axios, basePath));
        },
        /**
         *
         * @summary Get notifications for the current user
         * @param {NotificationControllerGetMyNotificationsTypeEnum} [type] Filter by notification type
         * @param {boolean} [isRead] Filter by read status
         * @param {number} [limit] Limit results
         * @param {number} [offset] Offset results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerGetMyNotifications(
            type?: NotificationControllerGetMyNotificationsTypeEnum,
            isRead?: boolean,
            limit?: number,
            offset?: number,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<void> {
            return localVarFp
                .notificationControllerGetMyNotifications(type, isRead, limit, offset, options)
                .then(request => request(axios, basePath));
        },
        /**
         *
         * @summary Get unread notification count for current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerGetMyUnreadCount(
            options?: RawAxiosRequestConfig
        ): AxiosPromise<void> {
            return localVarFp
                .notificationControllerGetMyUnreadCount(options)
                .then(request => request(axios, basePath));
        },
        /**
         *
         * @summary Get unread notification count for a user (own count or admin access)
         * @param {string} userId User ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerGetUnreadCount(
            userId: string,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<void> {
            return localVarFp
                .notificationControllerGetUnreadCount(userId, options)
                .then(request => request(axios, basePath));
        },
        /**
         *
         * @summary Mark all notifications as read for a user (own notifications or admin access)
         * @param {string} userId User ID (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerMarkAllAsRead(
            userId: string,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<void> {
            return localVarFp
                .notificationControllerMarkAllAsRead(userId, options)
                .then(request => request(axios, basePath));
        },
        /**
         *
         * @summary Mark all notifications as read for the current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerMarkMyNotificationsAsRead(
            options?: RawAxiosRequestConfig
        ): AxiosPromise<void> {
            return localVarFp
                .notificationControllerMarkMyNotificationsAsRead(options)
                .then(request => request(axios, basePath));
        },
        /**
         *
         * @summary Update notification (mark as read/unread)
         * @param {string} id Notification ID (UUID)
         * @param {UpdateNotificationDto} updateNotificationDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationControllerUpdate(
            id: string,
            updateNotificationDto: UpdateNotificationDto,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<NotificationResponseDto> {
            return localVarFp
                .notificationControllerUpdate(id, updateNotificationDto, options)
                .then(request => request(axios, basePath));
        }
    };
};

/**
 * NotificationsApi - object-oriented interface
 * @export
 * @class NotificationsApi
 * @extends {BaseAPI}
 */
export class NotificationsApi extends BaseAPI {
    /**
     *
     * @summary Create a new notification
     * @param {CreateNotificationDto} createNotificationDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    public notificationControllerCreate(
        createNotificationDto: CreateNotificationDto,
        options?: RawAxiosRequestConfig
    ) {
        return NotificationsApiFp(this.configuration)
            .notificationControllerCreate(createNotificationDto, options)
            .then(request => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Delete a notification
     * @param {string} id Notification ID (UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    public notificationControllerDeleteNotification(id: string, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration)
            .notificationControllerDeleteNotification(id, options)
            .then(request => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get notification by ID
     * @param {string} id Notification ID (UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    public notificationControllerFindById(id: string, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration)
            .notificationControllerFindById(id, options)
            .then(request => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get notifications for a user (own notifications or admin access)
     * @param {string} userId User ID (UUID)
     * @param {NotificationControllerFindByUserTypeEnum} [type] Filter by notification type
     * @param {boolean} [isRead] Filter by read status
     * @param {number} [limit] Limit results
     * @param {number} [offset] Offset results
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    public notificationControllerFindByUser(
        userId: string,
        type?: NotificationControllerFindByUserTypeEnum,
        isRead?: boolean,
        limit?: number,
        offset?: number,
        options?: RawAxiosRequestConfig
    ) {
        return NotificationsApiFp(this.configuration)
            .notificationControllerFindByUser(userId, type, isRead, limit, offset, options)
            .then(request => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get notifications for the current user
     * @param {NotificationControllerGetMyNotificationsTypeEnum} [type] Filter by notification type
     * @param {boolean} [isRead] Filter by read status
     * @param {number} [limit] Limit results
     * @param {number} [offset] Offset results
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    public notificationControllerGetMyNotifications(
        type?: NotificationControllerGetMyNotificationsTypeEnum,
        isRead?: boolean,
        limit?: number,
        offset?: number,
        options?: RawAxiosRequestConfig
    ) {
        return NotificationsApiFp(this.configuration)
            .notificationControllerGetMyNotifications(type, isRead, limit, offset, options)
            .then(request => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get unread notification count for current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    public notificationControllerGetMyUnreadCount(options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration)
            .notificationControllerGetMyUnreadCount(options)
            .then(request => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get unread notification count for a user (own count or admin access)
     * @param {string} userId User ID (UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    public notificationControllerGetUnreadCount(userId: string, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration)
            .notificationControllerGetUnreadCount(userId, options)
            .then(request => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Mark all notifications as read for a user (own notifications or admin access)
     * @param {string} userId User ID (UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    public notificationControllerMarkAllAsRead(userId: string, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration)
            .notificationControllerMarkAllAsRead(userId, options)
            .then(request => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Mark all notifications as read for the current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    public notificationControllerMarkMyNotificationsAsRead(options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration)
            .notificationControllerMarkMyNotificationsAsRead(options)
            .then(request => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Update notification (mark as read/unread)
     * @param {string} id Notification ID (UUID)
     * @param {UpdateNotificationDto} updateNotificationDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    public notificationControllerUpdate(
        id: string,
        updateNotificationDto: UpdateNotificationDto,
        options?: RawAxiosRequestConfig
    ) {
        return NotificationsApiFp(this.configuration)
            .notificationControllerUpdate(id, updateNotificationDto, options)
            .then(request => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const NotificationControllerFindByUserTypeEnum = {
    TaskAssigned: 'task_assigned',
    TaskCompleted: 'task_completed',
    CommentAdded: 'comment_added',
    ProjectStatusChanged: 'project_status_changed',
    MessageReceived: 'message_received',
    MessageReply: 'message_reply',
    CallScheduled: 'call_scheduled',
    IncomingCall: 'incoming_call'
} as const;
export type NotificationControllerFindByUserTypeEnum =
    (typeof NotificationControllerFindByUserTypeEnum)[keyof typeof NotificationControllerFindByUserTypeEnum];
/**
 * @export
 */
export const NotificationControllerGetMyNotificationsTypeEnum = {
    TaskAssigned: 'task_assigned',
    TaskCompleted: 'task_completed',
    CommentAdded: 'comment_added',
    ProjectStatusChanged: 'project_status_changed',
    MessageReceived: 'message_received',
    MessageReply: 'message_reply',
    CallScheduled: 'call_scheduled',
    IncomingCall: 'incoming_call'
} as const;
export type NotificationControllerGetMyNotificationsTypeEnum =
    (typeof NotificationControllerGetMyNotificationsTypeEnum)[keyof typeof NotificationControllerGetMyNotificationsTypeEnum];
