/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CallResponseDto
 */
export interface CallResponseDto {
    /**
     * 
     * @type {string}
     * @memberof CallResponseDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CallResponseDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof CallResponseDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CallResponseDto
     */
    'type': CallResponseDtoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CallResponseDto
     */
    'status': CallResponseDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CallResponseDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof CallResponseDto
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof CallResponseDto
     */
    'startedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CallResponseDto
     */
    'endedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CallResponseDto
     */
    'scheduledStartTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof CallResponseDto
     */
    'scheduledEndTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof CallResponseDto
     */
    'roomName'?: string;
    /**
     * 
     * @type {object}
     * @memberof CallResponseDto
     */
    'initiator': object;
    /**
     * 
     * @type {Array<string>}
     * @memberof CallResponseDto
     */
    'participants': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CallResponseDto
     */
    'duration'?: number;
    /**
     * 
     * @type {number}
     * @memberof CallResponseDto
     */
    'maxParticipants'?: number;
}

export const CallResponseDtoTypeEnum = {
    Voice: 'voice',
    Video: 'video'
} as const;

export type CallResponseDtoTypeEnum = typeof CallResponseDtoTypeEnum[keyof typeof CallResponseDtoTypeEnum];
export const CallResponseDtoStatusEnum = {
    Scheduled: 'scheduled',
    Active: 'active',
    Ended: 'ended'
} as const;

export type CallResponseDtoStatusEnum = typeof CallResponseDtoStatusEnum[keyof typeof CallResponseDtoStatusEnum];


