/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CallSessionResponseDto
 */
export interface CallSessionResponseDto {
    /**
     * 
     * @type {string}
     * @memberof CallSessionResponseDto
     */
    'token': string;
    /**
     * 
     * @type {string}
     * @memberof CallSessionResponseDto
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof CallSessionResponseDto
     */
    'roomName': string;
    /**
     * 
     * @type {string}
     * @memberof CallSessionResponseDto
     */
    'identity': string;
    /**
     * 
     * @type {boolean}
     * @memberof CallSessionResponseDto
     */
    'isHost': boolean;
    /**
     * 
     * @type {object}
     * @memberof CallSessionResponseDto
     */
    'participantId'?: object;
}

