/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ChannelResponseDto
 */
export interface ChannelResponseDto {
    /**
     *
     * @type {string}
     * @memberof ChannelResponseDto
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ChannelResponseDto
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof ChannelResponseDto
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof ChannelResponseDto
     */
    type: ChannelResponseDtoTypeEnum;
    /**
     *
     * @type {string}
     * @memberof ChannelResponseDto
     */
    visibility: ChannelResponseDtoVisibilityEnum;
    /**
     *
     * @type {string}
     * @memberof ChannelResponseDto
     */
    topic?: string;
    /**
     *
     * @type {boolean}
     * @memberof ChannelResponseDto
     */
    isArchived: boolean;
    /**
     *
     * @type {string}
     * @memberof ChannelResponseDto
     */
    createdAt: string;
    /**
     *
     * @type {string}
     * @memberof ChannelResponseDto
     */
    updatedAt: string;
    /**
     *
     * @type {object}
     * @memberof ChannelResponseDto
     */
    creator?: object;
    /**
     *
     * @type {Array<string>}
     * @memberof ChannelResponseDto
     */
    members: Array<string>;
    /**
     *
     * @type {object}
     * @memberof ChannelResponseDto
     */
    workspace?: object;
    /**
     *
     * @type {object}
     * @memberof ChannelResponseDto
     */
    project?: object;
    /**
     *
     * @type {number}
     * @memberof ChannelResponseDto
     */
    messageCount?: number;
    /**
     *
     * @type {number}
     * @memberof ChannelResponseDto
     */
    unreadCount?: number;
    /**
     *
     * @type {object}
     * @memberof ChannelResponseDto
     */
    lastMessage?: object;
}

export const ChannelResponseDtoTypeEnum = {
    Text: 'text',
    Dm: 'dm',
    GroupDm: 'group_dm'
} as const;

export type ChannelResponseDtoTypeEnum =
    (typeof ChannelResponseDtoTypeEnum)[keyof typeof ChannelResponseDtoTypeEnum];
export const ChannelResponseDtoVisibilityEnum = {
    Public: 'public',
    Private: 'private'
} as const;

export type ChannelResponseDtoVisibilityEnum =
    (typeof ChannelResponseDtoVisibilityEnum)[keyof typeof ChannelResponseDtoVisibilityEnum];
