/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommentResponseDto
 */
export interface CommentResponseDto {
    /**
     * 
     * @type {string}
     * @memberof CommentResponseDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponseDto
     */
    'content': string;
    /**
     * 
     * @type {boolean}
     * @memberof CommentResponseDto
     */
    'isEdited': boolean;
    /**
     * 
     * @type {string}
     * @memberof CommentResponseDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponseDto
     */
    'updatedAt': string;
    /**
     * 
     * @type {object}
     * @memberof CommentResponseDto
     */
    'author': object;
    /**
     * 
     * @type {object}
     * @memberof CommentResponseDto
     */
    'task': object;
}

