/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateChannelDto
 */
export interface CreateChannelDto {
    /**
     * 
     * @type {string}
     * @memberof CreateChannelDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateChannelDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChannelDto
     */
    'type'?: CreateChannelDtoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateChannelDto
     */
    'visibility'?: CreateChannelDtoVisibilityEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateChannelDto
     */
    'topic'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChannelDto
     */
    'workspaceId': string;
    /**
     * 
     * @type {string}
     * @memberof CreateChannelDto
     */
    'projectId'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateChannelDto
     */
    'memberIds'?: Array<string>;
}

export const CreateChannelDtoTypeEnum = {
    Text: 'text',
    Dm: 'dm',
    GroupDm: 'group_dm'
} as const;

export type CreateChannelDtoTypeEnum = typeof CreateChannelDtoTypeEnum[keyof typeof CreateChannelDtoTypeEnum];
export const CreateChannelDtoVisibilityEnum = {
    Public: 'public',
    Private: 'private'
} as const;

export type CreateChannelDtoVisibilityEnum = typeof CreateChannelDtoVisibilityEnum[keyof typeof CreateChannelDtoVisibilityEnum];


