/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateMediaRoomDto
 */
export interface CreateMediaRoomDto {
    /**
     * Name of the media room
     * @type {string}
     * @memberof CreateMediaRoomDto
     */
    name: string;
    /**
     * Maximum number of participants allowed
     * @type {number}
     * @memberof CreateMediaRoomDto
     */
    maxParticipants?: number;
}
