/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateNotificationDto
 */
export interface CreateNotificationDto {
    /**
     * Title of the notification
     * @type {string}
     * @memberof CreateNotificationDto
     */
    'title': string;
    /**
     * Detailed message of the notification
     * @type {string}
     * @memberof CreateNotificationDto
     */
    'message': string;
    /**
     * Type of notification
     * @type {string}
     * @memberof CreateNotificationDto
     */
    'type': CreateNotificationDtoTypeEnum;
    /**
     * ID of the user to receive the notification
     * @type {string}
     * @memberof CreateNotificationDto
     */
    'userId': string;
    /**
     * ID of the related entity (task, project, etc.)
     * @type {string}
     * @memberof CreateNotificationDto
     */
    'relatedEntityId'?: string;
    /**
     * Type of the related entity
     * @type {string}
     * @memberof CreateNotificationDto
     */
    'relatedEntityType'?: string;
}

export const CreateNotificationDtoTypeEnum = {
    TaskAssigned: 'task_assigned',
    TaskCompleted: 'task_completed',
    CommentAdded: 'comment_added',
    ProjectStatusChanged: 'project_status_changed',
    MessageReceived: 'message_received',
    MessageReply: 'message_reply',
    CallScheduled: 'call_scheduled',
    IncomingCall: 'incoming_call'
} as const;

export type CreateNotificationDtoTypeEnum = typeof CreateNotificationDtoTypeEnum[keyof typeof CreateNotificationDtoTypeEnum];


