/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateWorkspaceDto
 */
export interface CreateWorkspaceDto {
    /**
     * 
     * @type {string}
     * @memberof CreateWorkspaceDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkspaceDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkspaceDto
     */
    'type'?: CreateWorkspaceDtoTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof CreateWorkspaceDto
     */
    'isPublic'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateWorkspaceDto
     */
    'memberIds'?: Array<string>;
}

export const CreateWorkspaceDtoTypeEnum = {
    Company: 'company',
    Team: 'team',
    Project: 'project',
    Community: 'community'
} as const;

export type CreateWorkspaceDtoTypeEnum = typeof CreateWorkspaceDtoTypeEnum[keyof typeof CreateWorkspaceDtoTypeEnum];


