/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateProjectDto
 */
export interface CreateProjectDto {
    /**
     *
     * @type {string}
     * @memberof CreateProjectDto
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof CreateProjectDto
     */
    workspaceId: string;
    /**
     *
     * @type {string}
     * @memberof CreateProjectDto
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof CreateProjectDto
     */
    status?: CreateProjectDtoStatusEnum;
    /**
     *
     * @type {string}
     * @memberof CreateProjectDto
     */
    priority?: CreateProjectDtoPriorityEnum;
    /**
     *
     * @type {string}
     * @memberof CreateProjectDto
     */
    startDate?: string;
    /**
     *
     * @type {string}
     * @memberof CreateProjectDto
     */
    endDate?: string;
    /**
     *
     * @type {string}
     * @memberof CreateProjectDto
     */
    deadline?: string;
    /**
     *
     * @type {number}
     * @memberof CreateProjectDto
     */
    budget?: number;
    /**
     *
     * @type {string}
     * @memberof CreateProjectDto
     */
    color?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof CreateProjectDto
     */
    memberIds?: Array<string>;
}

export const CreateProjectDtoStatusEnum = {
    Planning: 'planning',
    InProgress: 'in_progress',
    OnHold: 'on_hold',
    Completed: 'completed',
    Cancelled: 'cancelled'
} as const;

export type CreateProjectDtoStatusEnum =
    (typeof CreateProjectDtoStatusEnum)[keyof typeof CreateProjectDtoStatusEnum];
export const CreateProjectDtoPriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Urgent: 'urgent'
} as const;

export type CreateProjectDtoPriorityEnum =
    (typeof CreateProjectDtoPriorityEnum)[keyof typeof CreateProjectDtoPriorityEnum];
