/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateMessageDto
 */
export interface CreateMessageDto {
    /**
     *
     * @type {string}
     * @memberof CreateMessageDto
     */
    content: string;
    /**
     *
     * @type {string}
     * @memberof CreateMessageDto
     */
    channelId: string;
    /**
     *
     * @type {string}
     * @memberof CreateMessageDto
     */
    parentMessageId?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof CreateMessageDto
     */
    attachmentIds?: Array<string>;
    /**
     * Structured payload for embeds
     * @type {object}
     * @memberof CreateMessageDto
     */
    embedData?: object;
    /**
     *
     * @type {boolean}
     * @memberof CreateMessageDto
     */
    isSystemMessage?: boolean;
}
