/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateTaskDto
 */
export interface CreateTaskDto {
    /**
     * 
     * @type {string}
     * @memberof CreateTaskDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskDto
     */
    'projectId': string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskDto
     */
    'status'?: CreateTaskDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskDto
     */
    'priority'?: CreateTaskDtoPriorityEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskDto
     */
    'dueDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateTaskDto
     */
    'estimatedHours'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskDto
     */
    'assigneeId'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateTaskDto
     */
    'tags'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CreateTaskDto
     */
    'position'?: number;
}

export const CreateTaskDtoStatusEnum = {
    Todo: 'todo',
    InProgress: 'in_progress',
    InReview: 'in_review',
    Done: 'done',
    Cancelled: 'cancelled'
} as const;

export type CreateTaskDtoStatusEnum = typeof CreateTaskDtoStatusEnum[keyof typeof CreateTaskDtoStatusEnum];
export const CreateTaskDtoPriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Urgent: 'urgent'
} as const;

export type CreateTaskDtoPriorityEnum = typeof CreateTaskDtoPriorityEnum[keyof typeof CreateTaskDtoPriorityEnum];


