/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface JoinRoomDto
 */
export interface JoinRoomDto {
    /**
     * ID of the user joining the room
     * @type {string}
     * @memberof JoinRoomDto
     */
    userId: string;
    /**
     * Media constraints for the user
     * @type {object}
     * @memberof JoinRoomDto
     */
    mediaConstraints?: object;
}
