/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ManualPresenceUpdateDto
 */
export interface ManualPresenceUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof ManualPresenceUpdateDto
     */
    'status': ManualPresenceUpdateDtoStatusEnum;
}

export const ManualPresenceUpdateDtoStatusEnum = {
    Online: 'online',
    Offline: 'offline',
    Away: 'away',
    Busy: 'busy'
} as const;

export type ManualPresenceUpdateDtoStatusEnum = typeof ManualPresenceUpdateDtoStatusEnum[keyof typeof ManualPresenceUpdateDtoStatusEnum];


