/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MarkAsReadDto
 */
export interface MarkAsReadDto {
    /**
     * Message ID to mark as read up to. If not provided, marks all messages in channel as read
     * @type {string}
     * @memberof MarkAsReadDto
     */
    upToMessageId?: string;
}
