/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MediaRoomResponseDto
 */
export interface MediaRoomResponseDto {
    /**
     *
     * @type {string}
     * @memberof MediaRoomResponseDto
     */
    id: string;
    /**
     *
     * @type {Array<string>}
     * @memberof MediaRoomResponseDto
     */
    participants: Array<string>;
    /**
     *
     * @type {boolean}
     * @memberof MediaRoomResponseDto
     */
    isActive: boolean;
    /**
     *
     * @type {string}
     * @memberof MediaRoomResponseDto
     */
    createdAt: string;
}
