/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MessageResponseDto
 */
export interface MessageResponseDto {
    /**
     * 
     * @type {string}
     * @memberof MessageResponseDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MessageResponseDto
     */
    'content': string;
    /**
     * 
     * @type {boolean}
     * @memberof MessageResponseDto
     */
    'isEdited': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MessageResponseDto
     */
    'isDeleted': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MessageResponseDto
     */
    'isSystemMessage': boolean;
    /**
     * 
     * @type {string}
     * @memberof MessageResponseDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof MessageResponseDto
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof MessageResponseDto
     */
    'editedAt'?: string;
    /**
     * 
     * @type {object}
     * @memberof MessageResponseDto
     */
    'author': object;
    /**
     * 
     * @type {object}
     * @memberof MessageResponseDto
     */
    'channel': object;
    /**
     * 
     * @type {object}
     * @memberof MessageResponseDto
     */
    'parentMessage'?: object;
    /**
     * 
     * @type {Array<string>}
     * @memberof MessageResponseDto
     */
    'attachments': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof MessageResponseDto
     */
    'reactions': Array<string>;
}

