/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NotificationResponseDto
 */
export interface NotificationResponseDto {
    /**
     * 
     * @type {string}
     * @memberof NotificationResponseDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponseDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponseDto
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponseDto
     */
    'type': NotificationResponseDtoTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationResponseDto
     */
    'isRead': boolean;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponseDto
     */
    'relatedEntityId'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponseDto
     */
    'relatedEntityType'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponseDto
     */
    'createdAt': string;
    /**
     * User who owns this notification
     * @type {object}
     * @memberof NotificationResponseDto
     */
    'user': object;
}

export const NotificationResponseDtoTypeEnum = {
    TaskAssigned: 'task_assigned',
    TaskCompleted: 'task_completed',
    CommentAdded: 'comment_added',
    ProjectStatusChanged: 'project_status_changed',
    MessageReceived: 'message_received',
    MessageReply: 'message_reply',
    CallScheduled: 'call_scheduled',
    IncomingCall: 'incoming_call'
} as const;

export type NotificationResponseDtoTypeEnum = typeof NotificationResponseDtoTypeEnum[keyof typeof NotificationResponseDtoTypeEnum];


