/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PresenceResponseDto
 */
export interface PresenceResponseDto {
    /**
     * 
     * @type {string}
     * @memberof PresenceResponseDto
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof PresenceResponseDto
     */
    'status': PresenceResponseDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PresenceResponseDto
     */
    'statusSource': PresenceResponseDtoStatusSourceEnum;
    /**
     * 
     * @type {string}
     * @memberof PresenceResponseDto
     */
    'manualStatus'?: PresenceResponseDtoManualStatusEnum;
    /**
     * 
     * @type {object}
     * @memberof PresenceResponseDto
     */
    'lastSeenAt'?: object;
    /**
     * 
     * @type {string}
     * @memberof PresenceResponseDto
     */
    'timestamp': string;
}

export const PresenceResponseDtoStatusEnum = {
    Online: 'online',
    Offline: 'offline',
    Away: 'away',
    Busy: 'busy'
} as const;

export type PresenceResponseDtoStatusEnum = typeof PresenceResponseDtoStatusEnum[keyof typeof PresenceResponseDtoStatusEnum];
export const PresenceResponseDtoStatusSourceEnum = {
    Auto: 'auto',
    Manual: 'manual'
} as const;

export type PresenceResponseDtoStatusSourceEnum = typeof PresenceResponseDtoStatusSourceEnum[keyof typeof PresenceResponseDtoStatusSourceEnum];
export const PresenceResponseDtoManualStatusEnum = {
    Online: 'online',
    Offline: 'offline',
    Away: 'away',
    Busy: 'busy'
} as const;

export type PresenceResponseDtoManualStatusEnum = typeof PresenceResponseDtoManualStatusEnum[keyof typeof PresenceResponseDtoManualStatusEnum];


