/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProjectResponseDto
 */
export interface ProjectResponseDto {
    /**
     *
     * @type {string}
     * @memberof ProjectResponseDto
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ProjectResponseDto
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof ProjectResponseDto
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof ProjectResponseDto
     */
    status: ProjectResponseDtoStatusEnum;
    /**
     *
     * @type {string}
     * @memberof ProjectResponseDto
     */
    priority: ProjectResponseDtoPriorityEnum;
    /**
     *
     * @type {string}
     * @memberof ProjectResponseDto
     */
    startDate?: string;
    /**
     *
     * @type {string}
     * @memberof ProjectResponseDto
     */
    endDate?: string;
    /**
     *
     * @type {string}
     * @memberof ProjectResponseDto
     */
    deadline?: string;
    /**
     *
     * @type {number}
     * @memberof ProjectResponseDto
     */
    budget?: number;
    /**
     *
     * @type {string}
     * @memberof ProjectResponseDto
     */
    color?: string;
    /**
     *
     * @type {string}
     * @memberof ProjectResponseDto
     */
    createdAt: string;
    /**
     *
     * @type {string}
     * @memberof ProjectResponseDto
     */
    updatedAt: string;
    /**
     *
     * @type {object}
     * @memberof ProjectResponseDto
     */
    owner: object;
    /**
     *
     * @type {Array<string>}
     * @memberof ProjectResponseDto
     */
    members: Array<string>;
    /**
     *
     * @type {number}
     * @memberof ProjectResponseDto
     */
    taskCount?: number;
}

export const ProjectResponseDtoStatusEnum = {
    Planning: 'planning',
    InProgress: 'in_progress',
    OnHold: 'on_hold',
    Completed: 'completed',
    Cancelled: 'cancelled'
} as const;

export type ProjectResponseDtoStatusEnum =
    (typeof ProjectResponseDtoStatusEnum)[keyof typeof ProjectResponseDtoStatusEnum];
export const ProjectResponseDtoPriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Urgent: 'urgent'
} as const;

export type ProjectResponseDtoPriorityEnum =
    (typeof ProjectResponseDtoPriorityEnum)[keyof typeof ProjectResponseDtoPriorityEnum];
