/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QualityMetricsDto
 */
export interface QualityMetricsDto {
    /**
     * ID of the user reporting metrics
     * @type {string}
     * @memberof QualityMetricsDto
     */
    userId: string;
    /**
     * Quality metrics data
     * @type {object}
     * @memberof QualityMetricsDto
     */
    metrics: object;
}
