/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QualityMetricsResponseDto
 */
export interface QualityMetricsResponseDto {
    /**
     *
     * @type {number}
     * @memberof QualityMetricsResponseDto
     */
    bitrate: number;
    /**
     *
     * @type {number}
     * @memberof QualityMetricsResponseDto
     */
    packetLoss: number;
    /**
     *
     * @type {number}
     * @memberof QualityMetricsResponseDto
     */
    jitter: number;
    /**
     *
     * @type {number}
     * @memberof QualityMetricsResponseDto
     */
    rtt: number;
    /**
     *
     * @type {string}
     * @memberof QualityMetricsResponseDto
     */
    timestamp: string;
}
