/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ReadReceiptResponseDto
 */
export interface ReadReceiptResponseDto {
    /**
     * Success message
     * @type {string}
     * @memberof ReadReceiptResponseDto
     */
    message?: string;
    /**
     * Number of messages marked as read
     * @type {number}
     * @memberof ReadReceiptResponseDto
     */
    markedAsRead?: number;
}
