/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ScheduleCallDto
 */
export interface ScheduleCallDto {
    /**
     * 
     * @type {string}
     * @memberof ScheduleCallDto
     */
    'type': ScheduleCallDtoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ScheduleCallDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof ScheduleCallDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduleCallDto
     */
    'scheduledStartTime': string;
    /**
     * 
     * @type {string}
     * @memberof ScheduleCallDto
     */
    'scheduledEndTime'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScheduleCallDto
     */
    'invitedUserIds'?: Array<string>;
}

export const ScheduleCallDtoTypeEnum = {
    Voice: 'voice',
    Video: 'video',
    ScreenShare: 'screen_share'
} as const;

export type ScheduleCallDtoTypeEnum = typeof ScheduleCallDtoTypeEnum[keyof typeof ScheduleCallDtoTypeEnum];


