/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface StartCallDto
 */
export interface StartCallDto {
    /**
     *
     * @type {string}
     * @memberof StartCallDto
     */
    type: StartCallDtoTypeEnum;
    /**
     *
     * @type {string}
     * @memberof StartCallDto
     */
    title?: string;
    /**
     *
     * @type {boolean}
     * @memberof StartCallDto
     */
    withVideo?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof StartCallDto
     */
    withAudio?: boolean;
    /**
     *
     * @type {Array<string>}
     * @memberof StartCallDto
     */
    invitedUserIds?: Array<string>;
}

export const StartCallDtoTypeEnum = {
    Voice: 'voice',
    Video: 'video',
    ScreenShare: 'screen_share'
} as const;

export type StartCallDtoTypeEnum = (typeof StartCallDtoTypeEnum)[keyof typeof StartCallDtoTypeEnum];
