/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TaskResponseDto
 */
export interface TaskResponseDto {
    /**
     * 
     * @type {string}
     * @memberof TaskResponseDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof TaskResponseDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof TaskResponseDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskResponseDto
     */
    'status': TaskResponseDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TaskResponseDto
     */
    'priority': TaskResponseDtoPriorityEnum;
    /**
     * 
     * @type {string}
     * @memberof TaskResponseDto
     */
    'dueDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskResponseDto
     */
    'estimatedHours': number;
    /**
     * 
     * @type {number}
     * @memberof TaskResponseDto
     */
    'actualHours': number;
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskResponseDto
     */
    'tags'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof TaskResponseDto
     */
    'position'?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskResponseDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof TaskResponseDto
     */
    'updatedAt': string;
    /**
     * 
     * @type {object}
     * @memberof TaskResponseDto
     */
    'project': object;
    /**
     * 
     * @type {object}
     * @memberof TaskResponseDto
     */
    'assignee'?: object;
    /**
     * 
     * @type {object}
     * @memberof TaskResponseDto
     */
    'creator': object;
    /**
     * 
     * @type {number}
     * @memberof TaskResponseDto
     */
    'commentCount'?: number;
}

export const TaskResponseDtoStatusEnum = {
    Todo: 'todo',
    InProgress: 'in_progress',
    InReview: 'in_review',
    Done: 'done',
    Cancelled: 'cancelled'
} as const;

export type TaskResponseDtoStatusEnum = typeof TaskResponseDtoStatusEnum[keyof typeof TaskResponseDtoStatusEnum];
export const TaskResponseDtoPriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Urgent: 'urgent'
} as const;

export type TaskResponseDtoPriorityEnum = typeof TaskResponseDtoPriorityEnum[keyof typeof TaskResponseDtoPriorityEnum];


