/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateWorkspaceDto
 */
export interface UpdateWorkspaceDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkspaceDto
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkspaceDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkspaceDto
     */
    'type'?: UpdateWorkspaceDtoTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateWorkspaceDto
     */
    'isPublic'?: boolean;
}

export const UpdateWorkspaceDtoTypeEnum = {
    Company: 'company',
    Team: 'team',
    Project: 'project',
    Community: 'community'
} as const;

export type UpdateWorkspaceDtoTypeEnum = typeof UpdateWorkspaceDtoTypeEnum[keyof typeof UpdateWorkspaceDtoTypeEnum];


