/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateUserDto
 */
export interface UpdateUserDto {
    /**
     *
     * @type {string}
     * @memberof UpdateUserDto
     */
    firstName?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateUserDto
     */
    lastName?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateUserDto
     */
    phoneNumber?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateUserDto
     */
    department?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateUserDto
     */
    position?: string;
}
