/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateCallParticipantDto
 */
export interface UpdateCallParticipantDto {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCallParticipantDto
     */
    'isMuted'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCallParticipantDto
     */
    'isVideoEnabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCallParticipantDto
     */
    'isScreenSharing'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCallParticipantDto
     */
    'isHandRaised'?: boolean;
}

