/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateProjectDto
 */
export interface UpdateProjectDto {
    /**
     *
     * @type {string}
     * @memberof UpdateProjectDto
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateProjectDto
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateProjectDto
     */
    status?: UpdateProjectDtoStatusEnum;
    /**
     *
     * @type {string}
     * @memberof UpdateProjectDto
     */
    priority?: UpdateProjectDtoPriorityEnum;
    /**
     *
     * @type {string}
     * @memberof UpdateProjectDto
     */
    startDate?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateProjectDto
     */
    endDate?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateProjectDto
     */
    deadline?: string;
    /**
     *
     * @type {number}
     * @memberof UpdateProjectDto
     */
    budget?: number;
    /**
     *
     * @type {string}
     * @memberof UpdateProjectDto
     */
    color?: string;
}

export const UpdateProjectDtoStatusEnum = {
    Planning: 'planning',
    InProgress: 'in_progress',
    OnHold: 'on_hold',
    Completed: 'completed',
    Cancelled: 'cancelled'
} as const;

export type UpdateProjectDtoStatusEnum =
    (typeof UpdateProjectDtoStatusEnum)[keyof typeof UpdateProjectDtoStatusEnum];
export const UpdateProjectDtoPriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Urgent: 'urgent'
} as const;

export type UpdateProjectDtoPriorityEnum =
    (typeof UpdateProjectDtoPriorityEnum)[keyof typeof UpdateProjectDtoPriorityEnum];
