/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserResponseDto
 */
export interface UserResponseDto {
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    'role': UserResponseDtoRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    'status': UserResponseDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    'phoneNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    'department'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    'position'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    'profilePicture'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserResponseDto
     */
    'isEmailVerified': boolean;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    'lastLoginAt'?: string;
}

export const UserResponseDtoRoleEnum = {
    Admin: 'admin',
    ProjectManager: 'project_manager',
    TeamMember: 'team_member',
    Client: 'client'
} as const;

export type UserResponseDtoRoleEnum = typeof UserResponseDtoRoleEnum[keyof typeof UserResponseDtoRoleEnum];
export const UserResponseDtoStatusEnum = {
    Active: 'active',
    Inactive: 'inactive'
} as const;

export type UserResponseDtoStatusEnum = typeof UserResponseDtoStatusEnum[keyof typeof UserResponseDtoStatusEnum];


