/* tslint:disable */
// @ts-nocheck
/* eslint-disable */
/**
 * Crewdo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@crewdo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorkspaceResponseDto
 */
export interface WorkspaceResponseDto {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceResponseDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceResponseDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceResponseDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceResponseDto
     */
    'type': WorkspaceResponseDtoTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof WorkspaceResponseDto
     */
    'isPublic': boolean;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceResponseDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceResponseDto
     */
    'updatedAt': string;
    /**
     * 
     * @type {object}
     * @memberof WorkspaceResponseDto
     */
    'owner': object;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkspaceResponseDto
     */
    'members'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof WorkspaceResponseDto
     */
    'memberCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkspaceResponseDto
     */
    'channelCount'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkspaceResponseDto
     */
    'channels'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof WorkspaceResponseDto
     */
    'projectCount'?: number;
}

export const WorkspaceResponseDtoTypeEnum = {
    Company: 'company',
    Team: 'team',
    Project: 'project',
    Community: 'community'
} as const;

export type WorkspaceResponseDtoTypeEnum = typeof WorkspaceResponseDtoTypeEnum[keyof typeof WorkspaceResponseDtoTypeEnum];


